version: "3.8"

services:
  # Backend service
  backend:
    build: .
    container_name: quizlingo-backend
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    env_file:
      - .env
    environment:
      # Server Configuration
      - PORT=${PORT:-8080}
      - NODE_ENV=${NODE_ENV:-development}
      - HOST=${HOST:-0.0.0.0}

      # MongoDB Configuration
      - MONGO_URI=${MONGO_URI}

      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}

      # AI Configuration
      - SKIP_GEMINI=${SKIP_GEMINI:-false}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
      - GEMINI_API_URL=${GEMINI_API_URL}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_API_URL=${GROQ_API_URL}

      # Base URL
      - BASE_URL=${BASE_URL}

      # reCAPTCHA Configuration
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}

      # Cloudinary Configuration
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

      # Email Configuration
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}

      # Frontend Configuration
      - FRONTEND_URL=${FRONTEND_URL}

      # AssemblyAI Configuration
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - ASSEMBLYAI_UPLOAD_URL=${ASSEMBLYAI_UPLOAD_URL}
      - ASSEMBLYAI_TRANSCRIPT_URL=${ASSEMBLYAI_TRANSCRIPT_URL}

      # Notification Configuration
      - NOTIFICATION_SMTP_HOST=${NOTIFICATION_SMTP_HOST}
      - NOTIFICATION_SMTP_PORT=${NOTIFICATION_SMTP_PORT}
      - NOTIFICATION_SMTP_SECURE=${NOTIFICATION_SMTP_SECURE}
      - NOTIFICATION_SMTP_USER=${NOTIFICATION_SMTP_USER}
      - NOTIFICATION_SMTP_PASS=${NOTIFICATION_SMTP_PASS}
      - NOTIFICATION_SMTP_FROM=${NOTIFICATION_SMTP_FROM}

      # PayOS Configuration
      - PAYOS_CLIENT_ID=${PAYOS_CLIENT_ID}
      - PAYOS_API_KEY=${PAYOS_API_KEY}
      - PAYOS_CHECKSUM_KEY=${PAYOS_CHECKSUM_KEY}
      - PAYOS_BASE_URL=${PAYOS_BASE_URL}
      - PAYOS_RETURN_URL=${PAYOS_RETURN_URL}
      - PAYOS_CANCEL_URL=${PAYOS_CANCEL_URL}
      - PAYOS_WEBHOOK_URL=${PAYOS_WEBHOOK_URL}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - quizlingo-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:${PORT:-8080}/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  quizlingo-network:
    driver: bridge
